version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - ainventory-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://ainventory:ainventory@db:5432/ainventory
      - SECRET_KEY=your-secret-key-here
      - ENVIRONMENT=production
    depends_on:
      - db
    networks:
      - ainventory-network
    volumes:
      - ./src:/app/src
      - ./app:/app/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=ainventory
      - POSTGRES_USER=ainventory
      - POSTGRES_PASSWORD=ainventory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - ainventory-network

volumes:
  postgres_data:

networks:
  ainventory-network:
    driver: bridge
